### ISSUE TITLE
Unclear installation instructions

### ISSUE THREAD

**Issue by mrigger** [zhilongwang/PolymorphicCanaries#2]
Hi,

I want to build the project for LLVM, but failed since the instructions were unclear.

From which directory or directories do I have to execute the following commands? Do I need to download LLVM for this?

```
$ mkdir build && cd build
$ cmake ..
$ make
$ cd Compiler based Implementation/P-SSP
$ make
```

**Comment by bin2415** [comment]
Hi, you can build it from the directory named "compiler based implementation", which has the CMakeLists.txt.

Year, you should have the clang/llvm in your computer.

**Comment by mrigger** [comment]
Thanks for your quick response! Since the installation description does not mention how to configure the tool with LLVM, I tried the following (each line executed from the parent directory):
```
$ git clone https://github.com/llvm/llvm-project && cd llvm-project && mkdir build && cd build && cmake -DLLVM_ENABLE_PROJECTS=clang -G "Unix Makefiles" ../llvm
$ export LLVM_DIR=/llvm-project/
$ cd PolymorphicCanaries/Compiler\ based\ Implementation && mkdir build && cd build && cmake .. && make
```

I get some warnings and the following error:
```
CMake Error at P-SSP-NT/CMakeLists.txt:3 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
```
Note that I also tried `RUN export LLVM_DIR=/llvm-project/build`. 

Is this due to an incorrect LLVM version? Is the LLVM version that should be used described as part of the installation or the paper?

Thanks in advance!

**Comment by bin2415** [comment]
Hi, it seems that you have not built the llvm correctly. You only cmake the project and have not 'make && make install' yet.

--------------------
I build the project on the version 3.8

If you use llvm 7.0 or higher, you can modify the file StackDoubleProtector.cpp and StackDoubleProtector.cpp by correcting the include path of file "TargetLowering.h" and "TargetSubtargetInfo.h". They are in the subdirectory of "llvm/CodeGen" now.

**Comment by mrigger** [comment]
Hi, thanks for the instructions! Unfortunately, I was still not able to build the project. Here is an excerpt from the `Dockerfile` that I created:

```
RUN wget -O - http://releases.llvm.org/3.8.1/llvm-3.8.1.src.tar.xz | tar -xJ && mv llvm-3.8.1.src llvm
RUN cd llvm/tools && wget -O - http://releases.llvm.org/3.8.1/cfe-3.8.1.src.tar.xz | tar -xJ && mv cfe-3.8.1.src clang
RUN cd llvm && mkdir build && cd build &&  cmake ..
RUN cd llvm/build make -j4 && make install
RUN git clone https://github.com/zhilongwang/PolymorphicCanaries
RUN cd /PolymorphicCanaries/Runtime\ Environment && make
RUN cd /PolymorphicCanaries/Compiler\ based\ Implementation/ && mkdir build && cd build && cmake .. && make
```

The last building step fails:
```
Step 11/13 : RUN cd /PolymorphicCanaries/Compiler\ based\ Implementation/ && mkdir build && cd build && cmake .. && make
 ---> Running in c4ba5d3fe7c4
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /PolymorphicCanaries/Compiler based Implementation/build
Scanning dependencies of target SSPPassNT
[ 25%] Building CXX object P-SSP-NT/SSPPass2/CMakeFiles/SSPPassNT.dir/StackDoubleProtector2.cpp.o
/PolymorphicCanaries/Compiler based Implementation/P-SSP-NT/SSPPass2/StackDoubleProtector2.cpp:6:10: fatal error: llvm/CodeGen/TargetPassConfig.h: No such file or directory
 #include "llvm/CodeGen/TargetPassConfig.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [P-SSP-NT/SSPPass2/CMakeFiles/SSPPassNT.dir/StackDoubleProtector2.cpp.o] Error 1
P-SSP-NT/SSPPass2/CMakeFiles/SSPPassNT.dir/build.make:62: recipe for target 'P-SSP-NT/SSPPass2/CMakeFiles/SSPPassNT.dir/StackDoubleProtector2.cpp.o' failed
CMakeFiles/Makefile2:103: recipe for target 'P-SSP-NT/SSPPass2/CMakeFiles/SSPPassNT.dir/all' failed
make[1]: *** [P-SSP-NT/SSPPass2/CMakeFiles/SSPPassNT.dir/all] Error 2
make: *** [all] Error 2
Makefile:83: recipe for target 'all' failed
The command '/bin/sh -c cd /PolymorphicCanaries/Compiler\ based\ Implementation/ && mkdir build && cd build && cmake .. && make' returned a non-zero code: 2
make: *** [Makefile:13: build] Error 2
```
Could you please help me further?

**Comment by zhilongwang** [comment]
> Hi, thanks for the instructions! Unfortunately, I was still not able to build the project. Here is an excerpt from the `Dockerfile` that I created:
> 
> ```
> RUN wget -O - http://releases.llvm.org/3.8.1/llvm-3.8.1.src.tar.xz | tar -xJ && mv llvm-3.8.1.src llvm
> RUN cd llvm/tools && wget -O - http://releases.llvm.org/3.8.1/cfe-3.8.1.src.tar.xz | tar -xJ && mv cfe-3.8.1.src clang
> RUN cd llvm && mkdir build && cd build &&  cmake ..
> RUN cd llvm/build make -j4 && make install
> RUN git clone https://github.com/zhilongwang/PolymorphicCanaries
> RUN cd /PolymorphicCanaries/Runtime\ Environment && make
> RUN cd /PolymorphicCanaries/Compiler\ based\ Implementation/ && mkdir build && cd build && cmake .. && make
> ```
> The last building step fails:
> 
> ```
> Step 11/13 : RUN cd /PolymorphicCanaries/Compiler\ based\ Implementation/ && mkdir build && cd build && cmake .. && make
>  ---> Running in c4ba5d3fe7c4
> -- The C compiler identification is GNU 7.3.0
> -- The CXX compiler identification is GNU 7.3.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Warning (dev) in CMakeLists.txt:
>   No cmake_minimum_required command is present.  A line of code such as
> 
>     cmake_minimum_required(VERSION 3.10)
> 
>   should be added at the top of the file.  The version specified may be lower
>   if you wish to support older CMake versions for this project.  For more
>   information run "cmake --help-policy CMP0000".
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /PolymorphicCanaries/Compiler based Implementation/build
> Scanning dependencies of target SSPPassNT
> [ 25%] Building CXX object P-SSP-NT/SSPPass2/CMakeFiles/SSPPassNT.dir/StackDoubleProtector2.cpp.o
> /PolymorphicCanaries/Compiler based Implementation/P-SSP-NT/SSPPass2/StackDoubleProtector2.cpp:6:10: fatal error: llvm/CodeGen/TargetPassConfig.h: No such file or directory
>  #include "llvm/CodeGen/TargetPassConfig.h"
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [P-SSP-NT/SSPPass2/CMakeFiles/SSPPassNT.dir/StackDoubleProtector2.cpp.o] Error 1
> P-SSP-NT/SSPPass2/CMakeFiles/SSPPassNT.dir/build.make:62: recipe for target 'P-SSP-NT/SSPPass2/CMakeFiles/SSPPassNT.dir/StackDoubleProtector2.cpp.o' failed
> CMakeFiles/Makefile2:103: recipe for target 'P-SSP-NT/SSPPass2/CMakeFiles/SSPPassNT.dir/all' failed
> make[1]: *** [P-SSP-NT/SSPPass2/CMakeFiles/SSPPassNT.dir/all] Error 2
> make: *** [all] Error 2
> Makefile:83: recipe for target 'all' failed
> The command '/bin/sh -c cd /PolymorphicCanaries/Compiler\ based\ Implementation/ && mkdir build && cd build && cmake .. && make' returned a non-zero code: 2
> make: *** [Makefile:13: build] Error 2
> ```
> Could you please help me further?

Hello,

I am sorry about that, the "llvm/CodeGen/TargetPassConfig.h" is not necessary for our code, just remove it, then I suppose that you can compile it successfully. 

Best wishes,
Zhilong
